### ISSUE TITLE
Seek in video

### ISSUE THREAD

**Issue by qarkai** [back-to/liveproxy#21]
Hi @back-to,
Is it possible to add support for seek in video?
When I open YouTube video in mpv+youtube-dl (actually SMPlayer but it doesn't matter) I can jump to arbitrary timestamp and video starts to play on that timestamp almost immediately.
When I open the very same video using LiveProxy's url and jump to the same timestamp video hangs. It made sense when there was only live streaming using streamlink. But with youtube-dl support it's natural to select timestamp in video.

**Comment by back-to** [comment]
> Is it possible to add support for seek in video?

Youtube with Youtube-DL seems to work with a small reload lag,
but **I won't change anything to get it work on everything**.

You will have to adjust your Youtube-DL / Player settings.

> When I open the very same video using LiveProxy's url and jump to the same timestamp video hangs.

That is up to your Youtube-DL / Player settings.

> It made sense when there was only live streaming using streamlink. But with youtube-dl support it's natural to select timestamp in video.

LiveProxy is there to redirect a Video to an URL when you can't use Streamlink / Youtube-DL on your device easily.

If you can use Streamlink / Youtube-DL on your device.
**Use them directly instead of LiveProxy.**
