### ISSUE TITLE
Allowed IP 

### ISSUE THREAD

**Issue by gr8rehanna** [back-to/liveproxy#37]
Hi, 

Thanks i have been using this to restream some stuff from twitch and Dailymotion.

Now i notice some streams that i have not started are running in background.

Anyone who has my port and IP can start pulling streams.
Can we implement option like. 
Allowed US : Only allowed user-agents allowed.
Allowed IP: Only allow client to play if clients ip is in allowed list. 

Also i have a custom made yt-dlp  i.e yt-pro 
now liveproxy doesn't understand yt-pro and solutions.

**Comment by back-to** [comment]
> Anyone who has my port and IP can start pulling streams.

because this tool is only meant for **local network** use or with a privat vpn into your network

**There are no safty features, if you open ports from your network**

> Can we implement option like.
Allowed US : Only allowed user-agents allowed.
Allowed IP: Only allow client to play if clients ip is in allowed list.

No, don't use this with open ports.

> Also i have a custom made yt-dlp

just use the default name, don't use something new.
